Import tool:  * add support for non-string value types (all except blob)  * support user-defined IDs for records & record updating  * allow unquoted field names and comments in the "json"
Updated to newer HBase snapshot for no particular reason.

Updated to latest SOLR, just because we can.

FieldTypeNotFoundException: fix 'todo' in case of getFieldTypeByName


git-svn-id: svn+ssh://dev.outerthought.org/outerthought/lilyproject/projects/lily/trunk@4130 b80d95f8-e103-0410-bd55-e03a9dc29394